### ISSUE TITLE
[Swift 3] Problem with setting lazy public vars

### ISSUE THREAD

**Issue by ruudk** [ArtSabintsev/Siren#112]
I'm trying to set some lazy public vars (appName, debugEnabled). This worked fine in Swift 2.3 but now when upgrading to Swift 3, it fails:

```swift
let siren = Siren.sharedInstance
        
siren.appName = "AppName"
siren.debugEnabled = true
siren.alertType = .option
siren.checkVersion(checkType: .daily)
```

It gives the following compile error:
```
Undefined symbols for architecture x86_64:
  "direct field offset for Siren.Siren.(appName.storage in _7DFB1BC200A6C64FBED860A3A8153B65) : Swift.String?", referenced from:
      Production.AppDelegate.checkForUpdates () -> () in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing Recent Issues
  "direct field offset for Siren.Siren.(appName.storage in _7DFB1BC200A6C64FBED860A3A8153B65) : Swift.String?", referenced from:


      Production.AppDelegate.checkForUpdates () -> () in AppDelegate.o


ld: symbol(s) not found for architecture x86_64


clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

When I remove the public vars and just do:
```swift
let siren = Siren.sharedInstance

//siren.appName = "AppName"
//siren.debugEnabled = true
siren.alertType = .option
siren.checkVersion(checkType: .daily)
```

it compiles.

Any idea?

**Comment by ArtSabintsev** [comment]
I cannot reproduce this issue in the Sample App. I added:

```swift
siren.appName = "Test"
```

and it compiled without issue in the Swift 3 master branch in Xcode 8.2.

**Comment by ArtSabintsev** [comment]
Closing this issue, but feel free to respond, and I will follow up as well (if needed).

**Comment by manishpathak99** [comment]
Using Xcode Version 8.1 ,  I am facing same issue Compilation error -
```
let appName = "My App"
siren.appName = appName

```

```
Undefined symbols for architecture x86_64:
  "direct field offset for Siren.Siren.(appName.storage in _7DFB1BC200A6C64FBED860A3A8153B65) : Swift.String?", referenced from:
      AppDelegate.setupSiren () -> () in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ArtSabintsev** [comment]
@manishpathak99 The latest version of Siren has been tested with Xcode 8.3.3. If you want a version of Siren that works with older version of Xcode, or older version of Swift, try the `swift2.3` branch.

I do not add any additional support of the library for older versions of Xcode of Swift outside of what's already in place.
